apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: node-exporter
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 1.3.1
    prometheus: k8s
    role: alert-rules
  name: k8s-alertrule-prometheusrule-aimotive
  namespace: monitoring
spec:
  groups:
  - name: node-exporter
    rules:
    - alert: TooManyPods
      annotations:
        description: Filesystem is running too many pods.
        runbook_url: https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubelettoomanypods/
        summary: Filesystem is currently running too many non-system namespace pods.
      expr: |
        (
          count(kube_pod_info) - count(kube_pod_info{namespace="kube-system"}) > 15
        )
      for: 5s
      labels:
        severity: warning